version: "3.8"
services:
  postgres:
    container_name: postgres_containerCA218
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_containerCA218
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: shuuriye@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5051:80"
